### PR TITLE
fix(2777): use option_env for trackers

### LINKED ISSUE #2777: Use `option_env!` to capture GA secrets from the env variable from CI
Currently the GA Secrets and Measurement ID is embeded in code, we would like to embed it at compile time instead via Github Secrets.

### PR DESCRIPTION
**Pull request by neo773**
**Issue Reference(s):**  
Fixes #2777

**Build & Testing:**

- [x] I ran `cargo test` successfully.
- [x] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

/claim #2777

### CODE REVIEW

File: tailcall-tracker/src/tracker.rs [hunk 1]
```diff
@@ -4,8 +4,16 @@ use super::Result;
...
-const MEASUREMENT_ID: &str = "G-JEP3QDWT0G";
+const API_SECRET: &str = match option_env!("GA_API_SECRET") {
+    Some(val) => val,
+    None => "dev",
+};
+
+const MEASUREMENT_ID: &str = match option_env!("GA_MEASUREMENT_ID") {
+    Some(val) => val,
+    None => "dev",
+};
```
Comment (tusharmath) [inline tailcall-tracker/src/tracker.rs:15]: CI also needs to be updated with the env variables being set.

**Review by tusharmath — APPROVED** [review]

File: tailcall-tracker/src/tracker.rs (hunk 1 above)
Comment (Hridoy000368) [reply tailcall-tracker/src/tracker.rs:15]: @ridoyshak35
