### PR TITLE
fix: dedupe dead-lock on dropped requests

### LINKED ISSUE #2276: bug: Tailcall with deduplication doesn't respond after making multiple concurrent requests
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug
On `dedupe:true`, If I make multiple concurrent n+1 query requests It doesn't respond.

### Steps to reproduce

1. Open codespace on https://github.com/tailcallhq/graphql-benchmarks
2. use `dedupe: true` in `graphql/tailcall/benchmark.graphql`
3. run the `./run.sh` script or `tailcall start benchmark.graphql` (for better logs)
4. In `wrk/wrk.lua` change `wrk.body` to `'{"operationName":null,"variables":{},"query":"{posts{id,userId,title,user{id,name,email}}}"}'
`
5. run `./wrk/bench.sh`.

### Expected behavior

Tailcall should respond and the benchmarks should work all the time.

### Actual behavior

On the first run of `./wrk/bench.sh` it might work correctly but try running it 2-3 more times. It doesn't respond and the benchmark shows all 0

### Screenshots

https://github.com/tailcallhq/tailcall/assets/73148455/7905b2de-45f0-419e-ad58-ef873ae772c3

### Environment information:

- **Operating System**: Github codespace
- **Tailcall Version**: 0.92.6
- **Rust Version**: rustc 1.79.0

### Additional context

I'm working on https://github.com/tailcallhq/graphql-benchmarks/pull/258

### PR DESCRIPTION
**Pull request by meskill**
**Summary:**  
_Briefly describe the changes made in this PR._

**Issue Reference(s):**  
Fixes #2276

**Build & Testing:**

- [ ] I ran `cargo test` successfully.
- [ ] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [ ] I have added relevant unit & integration tests.
- [ ] I have updated the [documentation] accordingly.
- [ ] I have performed a self-review of my code.
- [ ] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

### CODE REVIEW

File: src/core/data_loader/dedupe.rs [hunk 1]
```diff
@@ -185,4 +229,59 @@ mod tests {
...
+
+        cache
+            .dedupe(&1, move || async move {
+                sleep(Duration::from_millis(100)).await;
+            })
+            .await;
+    }
+
+    #[tokio::test]
+    async fn test_hanging_dropped_while_in_use() {
```
Comment (tusharmath) [inline src/core/data_loader/dedupe.rs:256]: This is is better than the `test_hanging_after_dropped` test. Can we drop the above one?
