### PR TITLE
fix duplicate sha getting published in memory registry

### LINKED ISSUE #206: InMemory persistence: Multiple instances for same sha is getting published

### PR DESCRIPTION
**Pull request by amitksingh1490**
Fixes #206

### CODE REVIEW

File: registry/src/main/scala/tailcall/registry/MemoryRegistry.scala [hunk 1]
```diff
@@ -1,12 +1,16 @@
...
+import zio.{Ref, Task, UIO, ZIO}
 
 final case class MemoryRegistry(ref: Ref[List[(String, Blueprint)]]) extends SchemaRegistry {
   override def add(blueprint: Blueprint): Task[Digest] = {
     val digest: Digest = blueprint.digest
-    ref.update((digest.hex -> blueprint) :: _).as(digest)
+    ref.get.map(_.find(_._1 == digest.hex)).flatMap {
+      case Some(_) => ZIO.succeed(digest)
+      case None    => ref.update((digest.hex -> blueprint) :: _).as(digest)
+
```
Comment (tusharmath) [inline registry/src/main/scala/tailcall/registry/MemoryRegistry.scala:12]:
```suggestion
```

**Review by tusharmath — APPROVED** [review]
