### PR TITLE
fix: disable batching when delay is set to 0

### LINKED ISSUE #737: There shouldn't be any batching when batch.delay is set to 0
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug
When `batch: {delay: 0}` is set in the config no batching should occur.

### Steps to reproduce

1. Run the benchmarks with and without `batch: {delay: 0}` added in the config
2. Run the benchmarks with and without `batch: {delay: 1}` added in the config

### Expected behavior

There shouldn't be any difference in performance between both the benchmarks in the first step.
In the second step, the one with batching enabled should be faster.

### Actual behavior

Both `batch: {delay: 0}` and `batch: {delay: 1}` give similar performance

### Environment information:

- **Ubuntu 22.04 LTS**
- **Tailcall version v0.17.0**
- **rustc 1.74.1**
- **wrk/4.1.0-3**

### PR DESCRIPTION
**Pull request by adelinaenache**
**Summary:**  
Make multiple requests when `upstream.batch.delay` is 0. 
If the graphql schema expects a single entry for a field but the result from the endpoint is an array with a single value, extract the value from the array.

**Issue Reference(s):**  
Fixes #737 
/claim #737 
**Build & Testing:**

- [x] I ran `cargo test` successfully.
- [x] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [x] I have added relevant unit & integration tests.
- [x] I have updated the documentation accordingly (if applicable).
- [x] I have performed a self-review of my own code.

### CODE REVIEW

File: src/blueprint/into_schema.rs [hunk 1]
```diff
@@ -48,13 +48,20 @@ fn to_type(def: &Definition) -> dynamic::Type {
             }
             Some(expr) => {
               let expr = expr.to_owned();
+              let field_of_type = type_ref.clone();
```
Comment (tusharmath) [inline src/blueprint/into_schema.rs:51]: Why do we need these changes?

File: src/http/request_context.rs [hunk 2]
```diff
@@ -91,6 +93,10 @@ impl RequestContext {
       self.set_min_max_age(-1);
     }
   }
+
+  pub fn is_batching_enabled(&self) -> bool {
+    return self.upstream.batch.is_some() && self.upstream.get_delay() != 0;
```
Comment (tusharmath) [inline src/http/request_context.rs:98]: Enable only if delay is >= 1 or max_size >= 1

File: src/http/request_context.rs [hunk 3]
```diff
@@ -25,9 +25,11 @@ pub struct RequestContext {
 impl Default for RequestContext {
   fn default() -> Self {
     let config = config::Config::default();
+    let mut upstream = config.upstream.clone();
+    upstream.batch = Some(Batch::default());
     //TODO: default is used only in tests. Drop default and move it to test.
     let server = Server::try_from(config.server.clone()).unwrap();
-    RequestContext::new(Arc::new(DefaultHttpClient::default()), server, config.upstream.clone())
+    RequestContext::new(Arc::new(DefaultHttpClient::default()), server, upstream)
```
Comment (tusharmath) [inline src/http/request_context.rs:32]: Why do we need these changes?

**Comment by tusharmath** [comment]
@adelinaenache can you please add integration tests in the `/tests/http` directory also.

File: src/blueprint/into_schema.rs (hunk 1 above)
Comment (adelinaenache) [reply src/blueprint/into_schema.rs:51]: The problem was that for the '/users&id=?` request the endpoint was returning an array but the GQL schema was expecting a single object, therefore returning an error to the GQL query.
 Before making this change, the request would go through the batched DataLoader that would take the array and process it, but now the response would only be processed by this future field resolver that did not expect to receive an array. 
 
My approach to this was to check the expected field type, and if was a single object but the response from the REST API was an array, extract the object from the array. Hope this is the right place to do it, if not please let me know how to approach this, thanks! 

This specific line was added because i needed the type of the field in a `match` context.

File: src/http/request_context.rs (hunk 3 above)
Comment (adelinaenache) [reply src/http/request_context.rs]: You are right, this was not needed.

File: tests/http/batching-disabled.yml [hunk 4]
```diff
@@ -0,0 +1,51 @@
+---
+config: !file tests/http/config/batching-disabled.graphql
```
Comment (tusharmath) [inline tests/http/batching-disabled.yml:2]: can use `!inline` and inline the YML here.

File: tests/http/batching-disabled.yml [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+    response:
+      body:
+        - id: -1
+          name: "THIS SHOULD NOT BE CALLED"
+  - request:
+      url: http://jsonplaceholder.typicode.com/users?id=2&id=1
+    response:
+      body:
+        - id: -1
+          name: "THIS SHOULD NOT BE CALLED"
```
Comment (amitksingh1490) [inline tests/http/batching-disabled.yml:68]: you can drop this as if the mock is not present the test will automatically fail

File: src/blueprint/into_schema.rs (hunk 1 above)
Comment (amitksingh1490) [reply src/blueprint/into_schema.rs:51]: Ideally this should not be done. It should fail as wrong URL is configured.

File: src/blueprint/into_schema.rs [hunk 6]
```diff
@@ -48,13 +48,20 @@ fn to_type(def: &Definition) -> dynamic::Type {
...
+
               FieldFuture::new(async move {
                 let ctx = EvaluationContext::new(req_ctx, &ctx);
                 let const_value = expr.eval(&ctx).await?;
                 let p = match const_value {
-                  ConstValue::List(a) => FieldValue::list(a),
+                  ConstValue::List(a) => match field_of_type {
+                    dynamic::TypeRef::Named(_) => FieldValue::from(a[0].clone()),
+                    dynamic::TypeRef::NonNull(_) => FieldValue::from(a),
+                    dynamic::TypeRef::List(_) => FieldValue::list(a),
```
Comment (amitksingh1490) [inline src/blueprint/into_schema.rs:60]: This is also not needed

**Review by amitksingh1490 — APPROVED** [review]
