### PR TITLE
fix: scalar not defined

### LINKED ISSUE #1497: bug: JSON not found
Using `JSON` in any type in the configuration fails currently even though it's defined as a scalar. 
This is true for all the scalars currently. Any custom scalar when used in the schema throws up this error. Eg:

```
ERROR Invalid Configuration
Caused by:
  • Type "Email" not found
```

**Technical Solution**
- Fix can be made by adding all the scalars into the Blueprint
- Add failing tests for this change

### PR DESCRIPTION
**Pull request by ssddOnTop**
**Summary:**  
_Briefly describe the changes made in this PR._

**Issue Reference(s):**  
Fixes #1497
/claim 1497

**Build & Testing:**

- [ ] I ran `cargo test` successfully.
- [ ] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [ ] I have added relevant unit & integration tests.
- [ ] I have updated the [documentation] accordingly.
- [ ] I have performed a self-review of my code.
- [ ] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `JSON` scalar type to represent JSON values, enhancing data representation flexibility in the schema.

- **Bug Fixes**
	- Fixed an issue where the `JSON` scalar type was incorrectly declared, ensuring proper adherence to the ECMA-404 standard.

- **Refactor**
	- Improved schema generation process by integrating custom scalar types more efficiently.

- **Tests**
	- Updated tests to include logging for better traceability during spec execution.

### CODE REVIEW

File: src/scalar/mod.rs [hunk 1]
```diff
@@ -32,12 +32,18 @@ lazy_static! {
     };
 }
 lazy_static! {
-    static ref SCALAR_TYPES: HashSet<&'static str> = {
+    pub static ref NON_PREMITIVE_SCALARS: HashSet<&'static str> = {
         let mut set = HashSet::new();
-        set.extend(["String", "Int", "Float", "Boolean", "ID", "JSON"]);
+        set.insert("JSON");
```
Comment (tusharmath) [inline src/scalar/mod.rs:37]: JSON should be a custom scala with validation returning true always.

File: tests/execution_spec.rs [hunk 2]
```diff
@@ -1012,6 +1012,7 @@ async fn assert_spec(spec: ExecutionSpec, opentelemetry: &InMemoryTelemetry) {
         let config = &server[0];
 
         // client: Check if client spec matches snapshot
+        println!("{:?}", spec.path);
```
Comment (tusharmath) [inline tests/execution_spec.rs:1015]:
```suggestion
        println!("{:?}", spec.path);
```

**Review by tusharmath — APPROVED** [review]
