### PR TITLE
fix: `DateTime` is not autogenerated in `.tailcallrc.graphql`

### LINKED ISSUE #2991: bug: `DateTime` is missing from `.tailcallrc.graphql`
The scalar `DateTime` is missing from the `.tailcallrc.graphql`

**Technical Requirements**
- Add DateTime to .tailcallrc.graphql
- Redesign/rearchitect it in a way such that adding a new scalar automatically update the schema file.

### PR DESCRIPTION
**Pull request by ssddOnTop**
**Issue Reference(s):**  
Fixes #2991

### CODE REVIEW

File: src/core/config/config.rs [hunk 1]
```diff
@@ -622,6 +622,7 @@ impl Config {
             .add_input(Telemetry::input_definition())
             .add_scalar(Scalar::Bytes.scalar_definition())
             .add_scalar(Scalar::Date.scalar_definition())
+            .add_scalar(Scalar::DateTime.scalar_definition())
```
Comment (tusharmath) [inline src/core/config/config.rs:625]: Use macros to add all scalars together instead of adding them one by one.

**Review by tusharmath — APPROVED** [review]
