### PR TITLE
fix: tailcall panics on SchemaError

### LINKED ISSUE #1478: bug: tailcall panics on SchemaError
Using a scalar `JSON` that's not defined causes a panic.

```
thread 'tokio-runtime-worker' panicked at src/blueprint/blueprint.rs:258:25:
called `Result::unwrap()` on an `Err` value: SchemaError("Type \"JSON\" not found")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /Users/tushar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/shutdown.rs:51:21:

```

**Expected**
Should fail grace fully with a validation error on the cli.

### PR DESCRIPTION
**Pull request by ssddOnTop**
**Summary:**  
_Briefly describe the changes made in this PR._

**Issue Reference(s):**  
Fixes #1478
/claim 1478

**Build & Testing:**

- [ ] I ran `cargo test` successfully.
- [ ] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [ ] I have added relevant unit & integration tests.
- [ ] I have updated the [documentation] accordingly.
- [ ] I have performed a self-review of my code.
- [ ] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

## Summary by CodeRabbit

- **Refactor**
	- Improved error handling across various components, including AWS Lambda Rust code, application context initialization, schema creation, server configuration, and schema validation in operations.
	- Enhanced error reporting in schema validation and operations, ensuring more robust application behavior.

### CODE REVIEW

File: src/blueprint/blueprint.rs [hunk 1]
```diff
@@ -255,6 +256,11 @@ impl Blueprint {
 
         // We should safely assume the blueprint is correct and,
         // generation of schema cannot fail.
-        schema.finish().unwrap()
+        Ok(Valid::from(
+            schema
+                .finish()
```
Comment (tusharmath) [inline src/blueprint/blueprint.rs:261]: We can call `finish` in `from_config.rs` once before returning the blueprint. That will capture all the errors before hand thus not needing to remove this unsafe unwrap call.

File: src/blueprint/from_config.rs [hunk 2]
```diff
@@ -121,8 +122,13 @@ impl TryFrom<&ConfigModule> for Blueprint {
     type Error = ValidationError<String>;
 
     fn try_from(config_module: &ConfigModule) -> Result<Self, Self::Error> {
-        config_blueprint()
+        let blueprint = config_blueprint()
             .try_fold(config_module, Blueprint::default())
-            .to_result()
+            .to_result()?;
```
Comment (tusharmath) [inline src/blueprint/from_config.rs:127]: use `and_then` on `Valid`.

**Review by tusharmath — APPROVED** [review]
