### PR TITLE
fix: npm release issue with windows

### LINKED ISSUE #647: tc.exe is not compatible with the version of Windows you're running
### Prerequisites

- [ ] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug

Installed `tailcal`l error on a 64-bit Windows operating system, installed the 32-bit `core-win32-x64-msvc`.

### Steps to reproduce

1. On a 64-bit platform running Windows 10
2. Execute the command: `npm i -g @tailcallhq/tailcall`
3. Execute the command: `tc`

### Expected behavior

Everything is fine.

### Actual behavior

A dialog box stating 'tc.exe failed to start or run. Please contact the software vendor to inquire about a version compatible with 64-bit Windows'

### Screenshots

image
image

### Environment information:

- **Operating System**:  Windows 10
- **Tailcall Version**:  last
- **Rust Version**:  -
- **GraphQL Client/version** (e.g., `curl/8.1.2`)

### Additional context

`@tailcallhq/core-win32-x64-msvc`  does not support 64-bit Windows programs

### PR DESCRIPTION
**Pull request by amitksingh1490**
Fix windows npm installation issue
fixes #647

### CODE REVIEW

File: npm/gen.ts [hunk 1]
```diff
@@ -39,7 +39,8 @@ async function genPlatformPackage() {
         keywords: keywords!,
         name: `@tailcallhq/core-${build}`,
         version,
-        directories: { bin: "bin" },
+        // directories: { bin: "bin" },
```
Comment (tusharmath) [inline npm/gen.ts:42]:
```suggestion
```

**Review by tusharmath — APPROVED** [review]

**Review by tusharmath — APPROVED** [review]
