### PR TITLE
fix: show log info instead of error when expected failure happens

### LINKED ISSUE #738: Show log info instead of error
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug
The `main` branch has an unexpected behavior on test execution. As shown on [this pipeline execution](https://github.com/tailcallhq/tailcall/actions/runs/7164375841/job/19504325802#step:6:344), we have an `http_spec` test that is logging `ERROR`, when there is no actual test failing.

### Steps to reproduce

1. Pull last changes from main
2. Run `cargo test`

### Expected behavior

The log should be `INFO http_spec] Graphql datasource your_file_path/tailcall/tests/http/graphql-dataloader-batch-keys.yml ... ok`

### Actual behavior

The log is `ERROR http_spec] Graphql datasource your_file_path/tailcall/tests/http/graphql-dataloader-batch-keys.yml ... failed`

### Screenshots
image

As mentioned by @amitksingh1490 
> this error shows that the test is supposed to fail and failing as expected.

### PR DESCRIPTION
**Pull request by ezhil56x**
**Summary:**  
Show log info instead of error

**Issue Reference(s):**  
Fixes #738
/claim #738

**Build & Testing:**

- [x] I ran `cargo test` successfully.
- [x] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [x] I have added relevant unit & integration tests.
- [ ] I have updated the [documentation] accordingly.
- [x] I have performed a self-review of my code.

[documentation]: https://github.com/tailcallhq/tailcall/tree/main/docs

### CODE REVIEW

File: tests/http_spec.rs [hunk 1]
```diff
@@ -354,7 +354,7 @@ async fn assert_downstream(spec: HttpSpec) {
           );
         }
         Err(_) => {
-          log::error!("{} {} ... failed", spec.name, spec.path.display());
+          log::info!("{} {} ... ok", spec.name, spec.path.display());
```
Comment (tusharmath) [inline tests/http_spec.rs:357]:
```suggestion
          log::info!("{} {} ... failed (expected)", spec.name, spec.path.display());
```

**Comment by ezhil56x** [comment]
@tusharmath Resolved!

**Review by tusharmath — APPROVED** [review]
