### PR TITLE
fix: resolve union type in response

### LINKED ISSUE #2020: bug: Using Union type in output generates validation error in runtime
### Prerequisites

- [ ] I have checked the existing issues to ensure this is not a duplicate.
- [ ] I am running the latest version of Tailcall.

### Describe the bug

Specifying union type as output generates error like below.

```
internal: invalid value for union \"FooBar\", expected \"FieldValue::WithType\"
```

### Steps to reproduce

I created a pr with changes in test related to unions https://github.com/tailcallhq/tailcall/pull/2019/files that demonstrates the issue.

### Additional Context

To be able to actually use unions `async_graphql` library requires to specify type name for every value that is returned as a union. Pr with test has commented code that fixes only test example and allows to get response properly but proper solution requires more general way to solve this.

### PR DESCRIPTION
**Pull request by meskill**
**Summary:**  
_Briefly describe the changes made in this PR._

**Issue Reference(s):**  
Fixes #2020 

**Build & Testing:**

- [ ] I ran `cargo test` successfully.
- [ ] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [ ] I have added relevant unit & integration tests.
- [ ] I have updated the [documentation] accordingly.
- [ ] I have performed a self-review of my code.
- [ ] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

### CODE REVIEW

File: src/core/blueprint/into_schema.rs [hunk 1]
```diff
@@ -34,14 +38,120 @@ fn to_type_ref(type_of: &Type) -> dynamic::TypeRef {
...
+/// Entity that analyzes resolved data and decides what variant type of union
+/// this data satisfies to. It's required to specify exact type in
+/// `async_graphql` otherwise validation error will be generated at runtime
+#[derive(Clone)]
+struct UnionTypeResolver {
+    type_name: String,
+    schemas: Arc<Option<Vec<(String, JsonSchema)>>>,
+}
+
+impl UnionTypeResolver {
```
Comment (tusharmath) [inline src/core/blueprint/into_schema.rs:50]: Let's move this to `union_resolver.rs`

File: src/core/blueprint/into_schema.rs [hunk 2]
```diff
@@ -34,14 +38,120 @@ fn to_type_ref(type_of: &Type) -> dynamic::TypeRef {
...
 }
 
-fn to_type(def: &Definition) -> dynamic::Type {
+/// Entity that analyzes resolved data and decides what variant type of union
+/// this data satisfies to. It's required to specify exact type in
+/// `async_graphql` otherwise validation error will be generated at runtime
+#[derive(Clone)]
+struct UnionTypeResolver {
+    type_name: String,
+    schemas: Arc<Option<Vec<(String, JsonSchema)>>>,
```
Comment (tusharmath) [inline src/core/blueprint/into_schema.rs:47]: Keep only a `Vec<(String, JsonSchema)>`

File: src/core/blueprint/into_schema.rs (hunk 1 above)
Comment (tusharmath) [reply src/core/blueprint/into_schema.rs:50]: I have a different proposal for this implementation. Ideally we would identify and store the discriminator while converting to blueprint. If we can't find the discriminator for a union type, we should throw a validation error, stating that there is no possible way to discriminate between the variants of the given union type.


Once we identify the discriminator we should create new IR:


```rust
enum IR {
  // ...
  Discriminate(Discriminator, Box<IR>)
  // ...
}

struct Discriminator(Vec<FieldName, TypeName>)

```

This particular IR when evaluated will check to identify the type of the output of the inner IR and store it in EvaluationCtx. In `into_schema` we can just read it and set it in the field value.

Let's discuss on discord if it isn't clear.

I feel this approach will be significantly superior to all existing Union type implementations.

**Review by tusharmath — CHANGES_REQUESTED** [review]
The union type check doesn't need to be a deep check. A discriminator needs to be identified and stored in the expression at compile time.

File: src/core/ir/evaluation_context.rs [hunk 3]
```diff
@@ -23,9 +24,11 @@ pub struct EvaluationContext<'a, Ctx: ResolverContextLike<'a>> {
 
     // Overridden Arguments for Async GraphQL Context
     graphql_ctx_args: Option<Arc<Value>>,
+
+    pub type_name: Option<TypeName>,
```
Comment (tusharmath) [inline src/core/ir/evaluation_context.rs:28]: Add some doc about what is being stored here.

File: src/core/ir/discriminator.rs [hunk 4]
```diff
@@ -0,0 +1,1054 @@
...
+    Vec(Vec<String>),
+}
+
+#[derive(Clone)]
+pub struct Discriminator {
+    types: Vec<String>,
+    fields_info: IndexMap<String, FieldInfo>,
+}
+
+impl std::fmt::Debug for Discriminator {
```
Comment (tusharmath) [inline src/core/ir/discriminator.rs:25]: Do we need the debugs?

File: src/core/ir/discriminator.rs [hunk 5]
```diff
@@ -0,0 +1,1054 @@
...
+use anyhow::{bail, Result};
+use async_graphql::Value;
+use indenter::indented;
+use indexmap::IndexMap;
+
+use crate::core::config::Type;
+use crate::core::valid::{Cause, Valid, Validator};
+
+#[derive(PartialEq, Eq, Debug, Clone)]
+pub enum TypeName {
```
Comment (tusharmath) [inline src/core/ir/discriminator.rs:14]: Can you add more documentation about what each type does and the overall algorithm.

File: src/core/ir/discriminator.rs (hunk 4 above)
Comment (meskill) [reply src/core/ir/discriminator.rs:25]: I'm suggesting to leave the debug fmt because it'll help in debugging since it outputs the info stored in `FieldInfo` as type name strings instead of raw usize. I've also added `tracing::debug!` in Discriminator in case we need to debug something in runtime

File: src/core/ir/evaluation_context.rs (hunk 3 above)
Comment (meskill) [reply src/core/ir/evaluation_context.rs:32]: added doc

File: src/core/ir/discriminator.rs (hunk 5 above)
Comment (meskill) [reply src/core/ir/discriminator.rs:19]: added more documentation

File: Cargo.toml [hunk 6]
```diff
@@ -159,6 +159,7 @@ base64 = "0.22.1"
 tailcall-hasher = { path = "tailcall-hasher" }
 serde_json_borrow = "0.3.0"
 Inflector = "0.11.4"
+indenter = "0.3.3"
```
Comment (tusharmath) [inline Cargo.toml:162]: Do we need this? It seems like it's only used to implement Debug.

File: src/core/valid/valid.rs [hunk 7]
```diff
@@ -157,6 +157,16 @@ impl<A, E> Valid<A, E> {
...
+impl<A: std::fmt::Debug, E: std::fmt::Debug> Valid<A, E> {
+    pub fn unwrap(self) -> A {
+        self.0.unwrap()
+    }
+
+    pub fn unwrap_err(self) -> ValidationError<E> {
+        self.0.unwrap_err()
+    }
+}
+
```
Comment (tusharmath) [inline src/core/valid/valid.rs:169]: can be moved to `test` config. Unwrap isn't a feature that Valid need to offer.

File: src/core/ir/discriminator.rs [hunk 8]
```diff
@@ -0,0 +1,1113 @@
...
+    }
+}
+
+/// Representation for set of types if some condition is hold.
+/// The condition is represented as a bit inside the usize number
+/// where bit position from the right in binary representation of usize
+/// is the index of type in the set and the if the value of the bit is
+/// 1 then the condition is hold
+#[derive(Copy, Clone, Default)]
+struct Repr(usize);
```
Comment (tusharmath) [inline src/core/ir/discriminator.rs:271]: Why not use a u128?

File: src/core/ir/discriminator.rs [hunk 9]
```diff
@@ -0,0 +1,1121 @@
...
+    }
+
+    /// Create new BitVec where condition is hold
+    /// for type with passed index
+    fn set_at(self, id: usize) -> Self {
+        Self(self.0 | (1 << id))
+    }
+
+    /// Search for first type in list for which condition is hold
+    fn first_covered_type<'types>(&self, types: &'types [String]) -> &'types str {
```
Comment (tusharmath) [inline src/core/ir/discriminator.rs:314]: We don't need to pass the slice of String to this BitVec. Keep the BitVec generic and multi-purpose.

File: src/core/ir/discriminator.rs [hunk 10]
```diff
@@ -0,0 +1,1121 @@
...
+        let mut result = Vec::new();
+
+        while x.0 != 0 {
+            result.push(x.first_covered_type(types));
+
+            *x = *x & (*x - 1);
+        }
+
+        result
+    }
```
Comment (tusharmath) [inline src/core/ir/discriminator.rs:330]: Two points:
1. We shouldn't bind the BitVec's implementation to this special usecase of array of strings.
2. Could we benefit from performance, if we mutated the original array in place?

File: src/core/ir/discriminator.rs (hunk 9 above)
Comment (tusharmath) [reply src/core/ir/discriminator.rs:314]: We need to have better bit_vec specific names here.

File: src/core/ir/discriminator.rs [hunk 11]
```diff
@@ -0,0 +1,1121 @@
...
+#[derive(Copy, Clone, Default)]
+struct BitVec(usize);
+
+impl std::fmt::Debug for BitVec {
+    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
+        f.write_fmt(format_args!("{:0b}", self.0))
+    }
+}
+
+impl Deref for BitVec {
```
Comment (tusharmath) [inline src/core/ir/discriminator.rs:279]: Not a good idea to implement Deref here. We should use Deref when the primary value is what's inside for eg: Box, Arc, Mutex etc. BitVec, is a great DS that encapsulates the idea of a vector for boolean values. We could have a `as_usize` method if really needed.

File: src/core/ir/discriminator.rs [hunk 12]
```diff
@@ -0,0 +1,1121 @@
...
+/// BitVecesents the type name for the resolved value.
+/// It is used when the GraphQL executor needs to resolve values of a union
+/// type. In order to select the correct fields, the executor must know the
+/// exact type name for each resolved value. And in cases when the output is
+/// list of union type it should resolve exact type for every entry in list.
+#[derive(PartialEq, Eq, Debug, Clone)]
+pub enum TypeName {
+    Single(String),
+    Vec(Vec<String>),
+}
```
Comment (tusharmath) [inline src/core/ir/discriminator.rs:22]: How about storing a ref of string?

File: src/core/ir/discriminator.rs [hunk 13]
```diff
@@ -0,0 +1,1121 @@
...
+        for (field, info) in &self.fields_info {
+            if obj.contains_key(field.as_str()) {
+                *possible_types &= *info.presented_in;
+            } else {
+                *possible_types &= !*info.required_in;
+            }
+
+            if possible_types.is_empty() {
+                // no possible types, something is wrong with the resolved value
+                bail!("Failed to find corresponding type for value")
```
Comment (tusharmath) [inline src/core/ir/discriminator.rs:246]: integration tests for all possible bailout conditions.

File: Cargo.toml (hunk 6 above)
Comment (meskill) [reply Cargo.toml:161]: yes, this only for debug, but debug is valuable

File: src/core/valid/valid.rs (hunk 7 above)
Comment (meskill) [reply src/core/valid/valid.rs:169]: since it easily could be done with `valid.to_result().unwrap()` anyway, is there a point of hiding it?

File: src/core/ir/discriminator.rs (hunk 8 above)
Comment (meskill) [reply src/core/ir/discriminator.rs:271]: u128 would imply using multiple registries and multiple cpu instructions to perform arithmetic operations while for usize I believe it is covered with single cpu registry and instruction

File: src/core/ir/discriminator.rs (hunk 11 above)
Comment (meskill) [reply src/core/ir/discriminator.rs]: replaced Deref/DerefMut with required operations traits

File: src/core/ir/discriminator.rs (hunk 12 above)
Comment (meskill) [reply src/core/ir/discriminator.rs:22]: The unconformable part is that async_graphql API requires 'static str or String to pass https://docs.rs/async-graphql/latest/async_graphql/dynamic/struct.FieldValue.html#method.with_type

I've put an experimental implementation as separate pr for this using `String::leak` here https://github.com/tailcallhq/tailcall/pull/2210

File: src/core/ir/discriminator.rs (hunk 9 above)
Comment (meskill) [reply src/core/ir/discriminator.rs:306]: if we want to have something multi-purpose for bitvec we can use https://docs.rs/bitvec/latest/bitvec/index.html.

But here I prefer to have specific implementation for this use-case since we can built more precise and more performant solution (ofc until usize repr is enough for us, otherwise bitvec should be better)

File: src/core/ir/discriminator.rs (hunk 10 above)
Comment (meskill) [reply src/core/ir/discriminator.rs:322]: 1. I'm not sure we should start premature abstractions at least until we have clear cases to do so. Bitvec representation have it's own drawbacks
2. I'm not sure I've got the question and what array do you mean?

File: src/core/ir/discriminator.rs (hunk 13 above)
Comment (meskill) [reply src/core/ir/discriminator.rs:248]: added tests

File: src/core/valid/valid.rs (hunk 7 above)
Comment (tusharmath) [reply src/core/valid/valid.rs:169]: We need to ask this question —
1. Is Valid a wrapper on Result?
2. Is Valid is a value that allows horizontal composition of errors?

If we consider definition 1, then yes, exposing the common Result methods on top of Valid makes sense. However if we consider that Valid is a type of its own and usage of Result type internally is merely an implementation detail, then exposing unwrap doesn't seem right. For eg: Let us change the implementation of Valid to not use a Result type but something custom, in that case we will have an overhead of supporting this API.

File: src/core/ir/discriminator.rs (hunk 11 above)
Comment (tusharmath) [reply src/core/ir/discriminator.rs]: Rust docs: https://doc.rust-lang.org/1.23.0/std/ops/trait.Deref.html
> Deref should only be implemented for smart pointers to avoid confusion.

Also look at — https://stackoverflow.com/questions/45086595/is-it-considered-a-bad-practice-to-implement-deref-for-newtypes

File: src/core/ir/eval.rs [hunk 14]
```diff
@@ -12,10 +12,10 @@ use crate::core::serde_value_ext::ValueExt;
 
 impl IR {
     #[tracing::instrument(skip_all, fields(otel.name = %self), err)]
-    pub fn eval<'a, Ctx>(
+    pub fn eval<'a, 'b, Ctx>(
         &'a self,
-        ctx: &'a mut EvalContext<'a, Ctx>,
-    ) -> Pin<Box<impl Future<Output = Result<ConstValue, Error>> + 'a>>
+        ctx: &'b mut EvalContext<'a, Ctx>,
+    ) -> Pin<Box<dyn Future<Output = Result<ConstValue, Error>> + Send + 'b>>
```
Comment (tusharmath) [inline src/core/ir/eval.rs:18]: IMPORTANT: This is introducing a dynamic dispatch. Please revert.

File: src/core/ir/discriminator.rs (hunk 11 above)
Comment (meskill) [reply src/core/ir/discriminator.rs]: well, there are mixed opinions on it based on discussion =)

But, I agree that we shouldn't overuse it and I've already replaced it

File: src/core/ir/eval.rs (hunk 14 above)
Comment (meskill) [reply src/core/ir/eval.rs:18]: I'm trying to resolve the issue about not having the Mutex in EvaluationContext here.

Since we removed Eval trait from main I'm struggling to fix the code now because of the errors rustc generates. I raised the discussion https://users.rust-lang.org/t/rpitit-allows-more-flexible-code-in-comparison-with-raw-rpit-in-inherit-impl/113417 about this. 

In short I can't specify impl here without breaking usage later because of the mutable reference to ctx. dyn works right now. Adding Eval trait will also solve this.

**Review by tusharmath — APPROVED** [review]
