### PR TITLE
fix(cache): @cache directive on types

### LINKED ISSUE #1279: Caching bug
### Observation

When the `@cache` directive is applied to the entire `Query` type, as shown in the first configuration, it doesn't enable caching for the egress requests made by the fields within the `Query` type. Specifically, the request made to `/posts` isn't cached:

```graphql
type Query @cache(maxAge: 30000) {
  posts: [Post] @http(path: "/posts")
}
```

In contrast, applying the `@cache` directive directly to the `posts` field within the `Query` type, as demonstrated below, successfully caches the egress request to `/posts`:

```graphql
type Query {
  posts: [Post] @http(path: "/posts") @cache(maxAge: 30000)
}
```

### Expected Behavior

The expectation is that applying the `@cache` directive at the `Query` type level should enable caching for all the egress IO operations defined within the `Query` type, for the specified `maxAge`. This means that all fields under the `Query` type should have their responses cached, based on the `maxAge` value provided in the `@cache` directive at the type level.

### PR DESCRIPTION
**Pull request by meskill**
**Summary:**  
Fixes usage of @cache directive specified on type level
close #1279

**Build & Testing:**

- [ ] I ran `cargo test` successfully.
- [ ] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

**Checklist:**

- [ ] I have added relevant unit & integration tests.
- [ ] I have updated the [documentation] accordingly.
- [ ] I have performed a self-review of my code.
- [ ] PR follows the naming convention of `<type>(<optional scope>): <title>`

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

### CODE REVIEW

File: autogen/src/gen_gql_schema.rs [hunk 1]
```diff
@@ -20,7 +20,7 @@ static DIRECTIVE_ALLOW_LIST: [(&str, Entity, bool); 13] = [
     ("groupBy", Entity::FieldDefinition, false),
     ("const", Entity::FieldDefinition, false),
     ("graphQL", Entity::FieldDefinition, false),
-    ("cache", Entity::FieldDefinition, false),
+    ("cache", Entity::ObjectOrFieldDefinition, false),
```
Comment (tusharmath) [inline autogen/src/gen_gql_schema.rs:23]:
```suggestion
    // Option 1
    ("cache", vec![Entity::ObjectOrFieldDefinition], false),
    // Option 2
    ("cache", Entity::List(Entity::Object, Entity::Field), false),
```

File: src/blueprint/definitions.rs [hunk 2]
```diff
@@ -344,8 +344,8 @@ pub fn update_cache_resolvers<'a>(
 ) -> TryFold<'a, (&'a ConfigModule, &'a Field, &'a config::Type, &'a str), FieldDefinition, String>
 {
     TryFold::<(&ConfigModule, &Field, &config::Type, &str), FieldDefinition, String>::new(
-        move |(_config, field, _, _name), mut b_field| {
-            if let Some(config::Cache { max_age }) = field.cache.as_ref() {
+        move |(_config, field, typ, _name), mut b_field| {
+            if let Some(config::Cache { max_age }) = field.cache.as_ref().or(typ.cache.as_ref()) {
```
Comment (tusharmath) [inline src/blueprint/definitions.rs:348]: We should have a unit test for it. I think the execution spec can be made to fail if an IO is made more than.

File: tests/execution/caching-gql-args.md
Comment (meskill) [inline tests/execution/caching-gql-args.md:1]: those tests seems outdated since the cache logic changed to focused on resolvers

File: tests/execution/caching.md [hunk 3]
```diff
@@ -1,23 +1,28 @@
 # Caching
 
+##### only
```
Comment (tusharmath) [inline tests/execution/caching.md:3]:
```suggestion
```

File: tests/execution/caching.md [hunk 4]
```diff
@@ -26,23 +31,52 @@ type Bar {
 ```yml
 - request:
     method: GET
-    url: http://example.com/bars
-    body: null
+    url: http://example.com/field-cache
+  assert_n: 1
```
Comment (tusharmath) [inline tests/execution/caching.md:35]: This should be set by default to 1, unless explicitly specified.

File: tests/execution_spec.rs [hunk 5]
```diff
@@ -254,6 +255,7 @@ enum ConfigSource {
 struct Mock {
     request: UpstreamRequest,
     response: UpstreamResponse,
+    assert_n: Option<usize>,
```
Comment (tusharmath) [inline tests/execution_spec.rs:258]: We are expecting `n` hits for this mock. Let's say that and add bit of documentation here about each field. 
```suggestion
    expect_hits: usize,
```
Set the default value to `1`.

File: tests/execution_spec.rs [hunk 6]
```diff
@@ -611,14 +609,61 @@ impl ExecutionSpec {
...
+    asserted_n: Arc<AtomicUsize>,
+}
+
+impl ExecutionMock {
+    fn assert_n(&self) {
+        if let Some(assert_n) = self.mock.assert_n {
+            assert_eq!(
+                assert_n,
+                self.asserted_n.load(Ordering::Relaxed),
+                "expected mock for {} to be called {assert_n} times",
```
Comment (tusharmath) [inline tests/execution_spec.rs:624]:
```suggestion
                "expected mock for {} to be hit exactly {assert_n} times",
```
