### PR TITLE
fix: `cors` type definitions in tailcallrc.graphql

### LINKED ISSUE #1607: bug: `Cors` has incorrect field requirements
`input Cors` in tailcallrc.graphql has a required value for `allowPrivateNetwork` and `allowCredentials`. They should not be required at all! Fix it :)

### PR DESCRIPTION
**Pull request by neo773**
**Summary:**  
_Briefly describe the changes made in this PR._

**Issue Reference(s):**  
Fixes #1607

**Build & Testing:**

- [x] I ran `cargo test` successfully.
- [x] I have run `./lint.sh --mode=fix` to fix all linting issues raised by `./lint.sh --mode=check`.

[documentation]: https://github.com/tailcallhq/tailcallhq.github.io/tree/develop/docs

/claim #1607

## Summary by CodeRabbit

- **New Features**
	- Enhanced flexibility in handling cross-origin requests by making `allowCredentials` and `allowPrivateNetwork` settings optional. This allows for more nuanced control over credentials and private network access in cross-origin scenarios.

### CODE REVIEW

File: src/config/cors.rs [hunk 1]
```diff
@@ -10,8 +10,8 @@ use crate::is_default;
 pub struct Cors {
     /// Indicates whether the server allows credentials (e.g., cookies,
     /// authorization headers) to be sent in cross-origin requests.
-    #[serde(default, skip_serializing_if = "is_default")]
```
Comment (tusharmath) [inline src/config/cors.rs:13]: should keep `skip_serializing_if`

File: tests/snapshots/execution_spec__cors-allow-cred-false.md_merged.snap [hunk 2]
```diff
@@ -2,7 +2,7 @@
 source: tests/execution_spec.rs
 expression: merged
 ---
-schema @server(headers: {cors: {allowHeaders: ["Authorization"], allowMethods: ["POST", "OPTIONS"], allowOrigins: ["abc.com", "xyz.com"], allowPrivateNetwork: true, maxAge: 23, vary: ["origin", "access-control-request-method", "access-control-request-headers"]}}) @upstream(baseURL: "http://example.com", batch: {delay: 1, headers: [], maxSize: 1000}) {
+schema @server(headers: {cors: {allowCredentials: false, allowHeaders: ["Authorization"], allowMethods: ["POST", "OPTIONS"], allowOrigins: ["abc.com", "xyz.com"], allowPrivateNetwork: true, maxAge: 23, vary: ["origin", "access-control-request-method", "access-control-request-headers"]}}) @upstream(baseURL: "http://example.com", batch: {delay: 1, headers: [], maxSize: 1000}) {
```
Comment (tusharmath) [inline tests/snapshots/execution_spec__cors-allow-cred-false.md_merged.snap:5]: The default value should not be inserted. The default should be false.

```suggestion
schema @server(headers: {cors: {allowHeaders: ["Authorization"], allowMethods: ["POST", "OPTIONS"], allowOrigins: ["abc.com", "xyz.com"], allowPrivateNetwork: true, maxAge: 23, vary: ["origin", "access-control-request-method", "access-control-request-headers"]}}) @upstream(baseURL: "http://example.com", batch: {delay: 1, headers: [], maxSize: 1000}) {
```

**Comment by tusharmath** [comment]
@neo773 Moving this to draft, until the comments are fixed.

**Review by tusharmath — APPROVED** [review]
