### PR TITLE
fix: docs trim from schema

### LINKED ISSUE #339: Docstrings are not preserved in the output schema
### Description
Docstrings in the tailcall configuration graphql file are not present in the generated schema, and so do not show up in tools like graphiql

### Steps to reproduce
Add a docstring in `jsonplaceholder.graphql`, for example

```graphql
schema
  @server(
    port: 8000
    baseURL: "http://jsonplaceholder.typicode.com"
    enableHttpCache: true
    enableGraphiql: "/graphiql"
    enableQueryValidation: false
  ) {
  query: Query
}

type Query {
  posts: [Post] @http(path: "/posts")
}

"""
This is a User
"""
type User {
  id: Int!
  name: String!
  username: String!
  email: String!
  phone: String
  website: String
}

"""
This is a Post
"""
type Post {
  id: Int!
  userId: Int!
  title: String!
  body: String!
  user: User @http(path: "/users/{{value.userId}}")
}
```

Run `tc start jsonplaceholder.graphql` and hit [http:://localhost:8000/graphiql](http:://localhost:8000/graphiql) and note that there are no dosctrings in the output schema.

### Expected behavior
Docstrings from the input graphql file are preserved in the final (output) schema.

### Actual behavior
No docstrings are present in the output schema

### PR DESCRIPTION
**Pull request by amitksingh1490**
**Issue Reference(s):**  
fixes #339 

**Build & Testing:**

- [x] The build is passing.
- [x] I have run `./lint.sh` to address and fix linting issues.

**Checklist:**

- [x] I have added relevant unit & integration tests.
- [x] I have updated the documentation accordingly (if applicable).
- [x] I have performed a self-review of my own code.

### CODE REVIEW

File: src/blueprint/into_schema.rs [hunk 1]
```diff
@@ -52,6 +52,9 @@ fn to_type(def: &Definition) -> dynamic::Type {
             }
           })
         });
+        if field.description.is_some() {
+          dyn_schema_field = dyn_schema_field.description(field.description.clone().unwrap());
```
Comment (tusharmath) [inline src/blueprint/into_schema.rs:56]: can use if let some instead.

**Review by tusharmath — APPROVED** [review]
